name: "Setup turborepo remote cache"
description: "Setup turborepo remote cache"
inputs:
  bucket:
    description: "Google cloud bucket to store remote cache"
    required: true

runs:
  using: "composite"
  steps:
    - name: TurboRepo Remote Cache Server
      uses: trappar/turborepo-remote-cache-gh-action@main
      with:
        storage-provider: google-cloud-storage
        storage-path: ${{ inputs.bucket }}
        team-id: team_fvst
        host: http://0.0.0.0
      env:
        LOG_LEVEL: "debug"
        BODY_LIMIT: "104857600"
        STORAGE_PATH_USE_TMP_FOLDER: "false"
