name: "Setup turborepo remote cache"
description: "Setup turborepo remote cache"
inputs:
  bucket:
    description: "Google cloud bucket to store remote cache"
    required: true
  google_cloud_token:
    description: "Base64 encoded token from secrets"
    required: true
  secret: # Read more at https://github.com/orgs/community/discussions/13082
    description: "Secret for passing encrypted secret values between jobs"
    required: true

runs:
  using: "composite"
  steps:
    - id: "google-key"
      name: "Unpack Key"
      shell: bash
      env:
        secret: ${{ inputs.secret }}
      run: |
        GOOGLE_CLOUD_TOKEN=$(echo ${{ inputs.google_cloud_token }} | base64 --decode)

        GOOGLE_CLOUD_PROJECT_ID_ENCRYPTED=$(gpg --symmetric --batch --passphrase "$secret" --output - <(echo "$GOOGLE_CLOUD_TOKEN" | jq -r '.project_id') | base64 -w0)
        echo "::add-mask::$GOOGLE_CLOUD_PROJECT_ID_ENCRYPTED"
        echo "::set-output name=GOOGLE_CLOUD_PROJECT_ID_ENCRYPTED::$GOOGLE_CLOUD_PROJECT_ID_ENCRYPTED"

        GOOGLE_CLOUD_CLIENT_PRIVATE_KEY_ENCRYPTED=$(gpg --symmetric --batch --passphrase "$secret" --output - <(echo "$GOOGLE_CLOUD_TOKEN" | jq -r '.private_key') | base64 -w0)
        echo "::add-mask::$GOOGLE_CLOUD_CLIENT_PRIVATE_KEY_ENCRYPTED"
        echo "::set-output name=GOOGLE_CLOUD_CLIENT_PRIVATE_KEY_ENCRYPTED::$GOOGLE_CLOUD_CLIENT_PRIVATE_KEY_ENCRYPTED"

        GOOGLE_CLOUD_CLIENT_EMAIL_ENCRYPTED=$(gpg --symmetric --batch --passphrase "$secret" --output - <(echo "$GOOGLE_CLOUD_TOKEN" | jq -r '.client_email') | base64 -w0)
        echo "::add-mask::$GOOGLE_CLOUD_CLIENT_EMAIL_ENCRYPTED"
        echo "::set-output name=GOOGLE_CLOUD_CLIENT_EMAIL_ENCRYPTED::$GOOGLE_CLOUD_CLIENT_EMAIL_ENCRYPTED"

    - name: Get GCP keys
      id: get_gcp_keys
      shell: bash
      env:
        secret: ${{ inputs.secret }}
      run: |
        GOOGLE_CLOUD_PROJECT_ID=$(gpg --decrypt --quiet --batch --passphrase "$secret" --output - <(echo "${{ steps.google-key.outputs.GOOGLE_CLOUD_PROJECT_ID_ENCRYPTED }}" | base64 --decode))
        echo "::add-mask::$GOOGLE_CLOUD_PROJECT_ID"
        GOOGLE_CLOUD_CLIENT_PRIVATE_KEY=$(gpg --decrypt --quiet --batch --passphrase "$secret" --output - <(echo "${{ steps.google-key.outputs.GOOGLE_CLOUD_CLIENT_PRIVATE_KEY_ENCRYPTED }}" | base64 --decode))
        echo "::add-mask::$GOOGLE_CLOUD_CLIENT_PRIVATE_KEY"
        GOOGLE_CLOUD_CLIENT_EMAIL=$(gpg --decrypt --quiet --batch --passphrase "$secret" --output - <(echo "${{ steps.google-key.outputs.GOOGLE_CLOUD_CLIENT_EMAIL_ENCRYPTED }}" | base64 --decode))
        echo "::add-mask::$GOOGLE_CLOUD_CLIENT_EMAIL"
    - name: TurboRepo Remote Cache Server
      uses: trappar/turborepo-remote-cache-gh-action@main
      with:
        storage-provider: google-cloud-storage
        storage-path: ${{ inputs.bucket }}
        team-id: team_fvst
      env:
        GCS_PROJECT_ID: ${{ env.GOOGLE_CLOUD_PROJECT_ID }}
        GCS_CLIENT_EMAIL: ${{ env.GOOGLE_CLOUD_CLIENT_PRIVATE_KEY }}
        GCS_PRIVATE_KEY: ${{ env.GOOGLE_CLOUD_CLIENT_EMAIL }}
