version: "3"
services:
  postgres:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: fvst
      POSTGRES_PASSWORD: fvst
      POSTGRES_DB: fvst
    volumes:
      - postgres-auth:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data

  gateway:
    image: ghcr.io/apollographql/router:v1.4.0
    restart: always
    environment:
      APOLLO_GRAPH_REF: ${APOLLO_GRAPH_REF}
      APOLLO_KEY: ${APOLLO_KEY}
    command: -c settings/router.yml
    ports:
      - "4000:4000"
    volumes:
      - ./apps/apollo-gateway/config:/dist/settings

volumes:
  postgres-auth:
  redis:
