version: "3"
services:
  postgres_auth:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: fvst
      POSTGRES_PASSWORD: fvst
      POSTGRES_DB: fvst
    volumes:
      - postgres-auth:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  postgres_web:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: fvst
      POSTGRES_PASSWORD: fvst
      POSTGRES_DB: fvst
    volumes:
      - postgres-web:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data
volumes:
  postgres-auth:
  postgres-web:
  redis:
