name: "Runs terraform apply in the appropriate environment"
description: "Runs terraform apply in the appropriate environment"
inputs:
  environment:
    description: "Environment name in lower case"
    required: true
  terraform-bucket:
    description: "The bucket we store the terraform state in"
    required: true
  region:
    description: "The region we are deploying too"
    required: true
  prefix:
    description: "The unix prefix we set up"
    required: true
runs:
  using: "composite"
  env:
    TF_VAR_project: ${{ vars.FVST_PROJECT_PREFIX }}-fvst-${{inputs.environment}}
    TF_VAR_region: ${{ vars.FVST_PROJECT_REGION }}
  steps:
    - name: Setup terraform remote and configuration
      run: |
        cat <<EOT >> "./infra/envs/${{inputs.environment}}/backend.tf"
          terraform {
            backend "gcs" {
              bucket = "${{ inputs.terraform-bucket }}"
            }
        }
        EOT
    - name: Terraform init
      working-directory: ./infra/envs/${{inputs.environment}}
      run: terraform init
    - name: Terraform apply
      working-directory: ./infra/envs/${{inputs.environment}}
      run: terraform apply -auto-approve
