name: Deploy
on: push

env:
  DOCKER_TAG: deploy-run-${{ github.run_number }}

jobs:
  prebuild:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: "actions/checkout@v3"
      - uses: ./.github/actions/services-matrix
        id: "matrix"

  deploy-staging:
    needs: prebuild
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prebuild.outputs.matrix) }}
    steps:
      - uses: "actions/checkout@v3"
      - name: "Configure env variables"
        run: |
          project="${{ vars.FVST_PROJECT_PREFIX }}-fvst-staging"
          registry="us-docker.pkg.dev/$project/registry"
          echo "project=$project" >> $GITHUB_ENV
          echo "registry=$registry" >> $GITHUB_ENV
      - uses: ./.github/actions/build-docker-container
        with:
          google_cloud_token: ${{ secrets.GOOGLE_CLOUD_TOKEN_STAGING }}
          turborepo_cache_bucket: ${{ vars.FVST_PROJECT_TURBOREPO_BUCKET_STAGING }}
          registry: ${{ env.registry }}
          service: ${{ matrix.service }}
          dockerfile: ${{ matrix.dockerfile }}
          tag: ${{ env.DOCKER_TAG }}
      - name: Deploy
        run: |
          gcloud --project ${{ env.project }} run deploy ${{ matrix.service }} --image ${{ env.registry }}/${{ env.service }}:$DOCKER_TAG --region ${{ vars.FVST_PROJECT_REGION }}
