name: Deploy
on: push

env:
  DOCKER_TAG: gh-run-${{ github.run_number }}

jobs:
  prebuild:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: "actions/checkout@v3"
      - uses: ./.github/actions/services-matrix
        id: "matrix"

  deploy:
    needs: prebuild
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJSON(needs.prebuild.outputs.matrix)}}
    steps:
      - uses: "actions/checkout@v3"
      - name: running
        run: echo "running job with ${{ matrix.service }} ${{ matrix.dockerfile }}"
