name: Google Branch

on:
  push:
    branches: [google-cloud]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: "actions/checkout@v3"

      - name: "Unpack Key"
        id: "google-key"
        run: |
          GOOGLE_CLOUD_TOKEN=$(echo ${{secrets.GOOGLE_CLOUD_TOKEN}} | base64 --decode)
          echo "GOOGLE_CLOUD_TOKEN=$GOOGLE_CLOUD_TOKEN" >> $GITHUB_OUTPUT

      - name: "Test Token"
        run: echo ${{steps.google-key.outputs.GOOGLE_CLOUD_TOKEN}}

      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: $(echo ${{secrets.GOOGLE_CLOUD_TOKEN}} | base64 --decode)

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: ">= 417.0.0"

      - name: "Use gcloud CLI"
        run: "gcloud info"
