name: Google Branch

on:
  push:
    branches: [google-cloud]

env:
  BILLING_ACCOUNT: "01AEBE-A2F4CA-DC0648"

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: "actions/checkout@v3"

      - name: "Unpack Key"
        id: "google-key"
        run: |
          GOOGLE_CLOUD_TOKEN=$(echo ${{secrets.GOOGLE_CLOUD_TOKEN}} | base64 --decode)
          echo "GOOGLE_CLOUD_TOKEN=$GOOGLE_CLOUD_TOKEN" >> $GITHUB_OUTPUT

      - name: "Test Token"
        run: echo ${{steps.google-key.outputs.GOOGLE_CLOUD_TOKEN}}

      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{steps.google-key.outputs.GOOGLE_CLOUD_TOKEN}}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: ">= 417.0.0"

      - name: "Create Project"
        run: |
          gcloud sql instances list
          gcloud projects create fvst-staging2 --name "FVST Staging" --folder=647530911223 --set-as-default

      - name: "Install support components"
        run: |
          gcloud components install alpha 
          gcloud components install beta

      - name: "Configure billing"
        run: |
          gcloud services enable cloudbilling.googleapis.com
          gcloud alpha billing projects link fvst-staging2 --billing-account 01AEBE-A2F4CA-DC0648

      - name: "Turn on features"
        run: gcloud services enable compute.googleapis.com sqladmin.googleapis.com run.googleapis.com containerregistry.googleapis.com cloudbuild.googleapis.com servicenetworking.googleapis.com vpcaccess.googleapis.com
