name: Initial Setup
on:
  workflow_dispatch:
    inputs:
      apollo-studio-key:
        description: "Apollo Studio API Key"
        required: true
      apollo-studio-graph-name:
        description: "Apollo Studio Supergraph Name"
        required: true
      railway-token:
        description: "Railway Token"
        required: true
      github-token:
        description: "Github Token"
        required: true

env:
  GITHUB_TOKEN: ${{ github.event.inputs.github-token }}
  RAILWAY_TOKEN: ${{github.event.inputs.railway-token }}
jobs:
  configure-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add Railway API Token
        run: gh secret set RAILWAY_TOKEN --app actions --body ${{github.event.inputs.railway-token }}

  configure-railway:
    runs-on: ubuntu-latest
    needs: configure-secrets
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make init executable
        run: chmod +x ./github/scripts/setup_railway_env.sh
      - name: Run railway setup
        run: ./github/scripts/setup_railway_env.sh
