name: Initial Setup
on:
  workflow_dispatch:
    inputs:
      apollo-studio-key:
        description: "Apollo Studio API Key"
        required: true
      apollo-studio-graph-name:
        description: "Apollo Studio Supergraph Name"
        required: true
      railway-api-key:
        description: "Railway API Key"
        required: true
      github-token:
        description: "Github Token"
        required: true

env:
  GITHUB_TOKEN: ${{ github.event.inputs.github-token }}
jobs:
  configure-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Add Apollo Studio Key to $GITHUB_REPOSITORY'
        run: gh api --method PUT /repos/$GITHUB_REPOSITORY/actions/secrets/SAMPLE_KEY -f encrypted_value='c2VjcmV0'

  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        run: echo "Hello ${{ github.event.inputs.apollo-studio-graph-name }}"
