name: Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Restore node_modules
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Install railway
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Login to railway
        run: |
          mkdir ~/.railway
          echo ${{secrets.RAILWAY_TOKEN}} | base64 --decode > ~/.railway/config.json
          echo | railway link 64af130d-0ed9-49af-be8d-e3e0b58468f0

      - name: Switch railway environment
        run: |
          echo "Switching to fvst-monorepo-pr-${{ github.event.number }}"
          railway environment fvst-monorepo-pr-${{ github.event.number }}

      - name: Configure Apollo Gateway
        run: |
          pwd
          ls -la
          railway -s apollo-gateway variables set APOLLO_GRAPH_REF="fvst-main@pr-${{ github.event.number }}" APOLLO_KEY=${{ secrets.APOLLO_KEY }} PORT=4000

      - name: Install rover
        run: curl -sSL https://rover.apollo.dev/nix/latest | sh

      - name: Sync schema
        run: |
          export APOLLO_GRAPH_REF="fvst-main@$pr-${{ github.event.number }}"
          export APOLLO_KEY=${{ secrets.APOLLO_KEY }}
          export PR_NUMBER=${{github.event.pull_request.number}}
          chmod +x apps/apollo-gateway/publish_ci_schema_updates.sh
          ./apps/apollo-gateway/publish_ci_schema_updates.sh
