name: Pull request
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Restore node_modules
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}

      - uses: ./.github/actions/setup-google-cloud-auth
        with:
          google_cloud_token: ${{ secrets.GOOGLE_CLOUD_TOKEN_STAGING }}

      - uses: ./.github/actions/setup-turborepo-remote-cache
        with:
          bucket: ${{ vars.FVST_PROJECT_TURBOREPO_BUCKET_STAGING }}

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
