name: Terraform plan
on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  staging:
    if: github.base_ref == 'develop'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup-google-cloud-auth
        with:
          google_cloud_token: ${{ secrets.GOOGLE_CLOUD_TOKEN_STAGING }}

      - name: "Run terraform plan against staging"
        uses: ./.github/actions/terraform-plan
        with:
          environment: "staging"
          terraform-bucket: ${{ vars.FVST_PROJECT_TF_STATE_BUCKET_STAGING }}
          region: ${{ vars.FVST_PROJECT_REGION }}
          prefix: ${{ vars.FVST_PROJECT_PREFIX }}
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          docker-tag: "latest"

  production:
    if: github.base_ref == 'main'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/setup-google-cloud-auth
        with:
          google_cloud_token: ${{ secrets.GOOGLE_CLOUD_TOKEN_PRODUCTION }}

      - name: "Run terraform plan against production"
        uses: ./.github/actions/terraform-plan
        with:
          environment: "production"
          terraform-bucket: ${{ vars.FVST_PROJECT_TF_STATE_BUCKET_PRODUCTION }}
          region: ${{ vars.FVST_PROJECT_REGION }}
          prefix: ${{ vars.FVST_PROJECT_PREFIX }}
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          docker-tag: "latest"
