name: Terraform
on: [push]

env:
  GH_TOKEN: ${{github.event.inputs.github-token }}

jobs:
  initialize:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: ["STAGING"]
    env:
      PROJECT: ${{ secrets.FVST_PROJECT_PREFIX }}-fvst-${{matrix.environment}}

    steps:
      - uses: "actions/checkout@v3"

      - name: Print info
        run: |
          echo "Using $PROJECT as project"

      - name: "Unpack Key"
        id: "google-key"
        run: |
          GOOGLE_CLOUD_TOKEN=$(echo ${{secrets.GOOGLE_CLOUD_TOKEN_${{ matrix.environment }} }} | base64 --decode)
          echo "GOOGLE_CLOUD_TOKEN=$GOOGLE_CLOUD_TOKEN" >> $GITHUB_OUTPUT

      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{steps.google-key.outputs.GOOGLE_CLOUD_TOKEN}}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Info
        run: gcloud info
